const mockedDescription =
    "Captain. Yes, sir? Tell them we wish to board at once. With all due respect, the Ambassadors for the Supreme Chancellor wish to board immediately. Yes, yes, of course, as you know, our blockade is perfectly legal, and we'd be happy to receive the Ambassador. The hyperdrive is leaking. We'll have to land somewhere to refuel and repair the ship. Here, Master. Tatooine, It's small, out of the way, poor. The Trade Federation has no presence there.";

const mockedCharacters = [
    {
        id: 1,
        name: "Luke Skywalker",
        gender: "Male",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/1.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 2,
        name: "C-3PO",
        gender: "n/a",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/2.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 3,
        name: "R2-D2",
        gender: "n/a",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/3.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 4,
        name: "Darth Vader",
        gender: "Male",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/4.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 5,
        name: "Leia Skywalker",
        gender: "Female",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/5.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 6,
        name: "Obi Wan Kenobi",
        gender: "Male",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/6.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 7,
        name: "Lady L",
        gender: "Female",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/7.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
];

const mockedFilms = [
    {
        id: 1,
        title: "A New Hope",
        cover: "https://starwars-visualguide.com/assets/img/films/1.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 2,
        title: "The Empire Strikes Back",
        cover: "https://starwars-visualguide.com/assets/img/films/2.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 3,
        title: "Return of the Jedi",
        cover: "https://starwars-visualguide.com/assets/img/films/3.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 4,
        title: "The Phantom Menace",
        cover: "https://starwars-visualguide.com/assets/img/films/4.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 5,
        title: "Attack of the Clones",
        cover: "https://starwars-visualguide.com/assets/img/films/5.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 6,
        title: "Revenge of the Sith",
        cover: "https://starwars-visualguide.com/assets/img/films/6.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
];

module.exports = { mockedFilms, mockedCharacters };
