const mockedDescription =
    "A sdfskdfj\n sdfhsjkdhfkjsadhfsjdf\n dsjfk sdkjfksdjfsd lfkjsafjs\nsdfsdfsd fsdfs";

const mockedCharacters = [
    {
        id: 1,
        name: "Luke Skywalker",
        gender: "Male",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/1.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 2,
        name: "C-3PO",
        gender: "n/a",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/2.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 3,
        name: "R2-D2",
        gender: "n/a",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/3.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 4,
        name: "Darth Vader",
        gender: "Male",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/4.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 5,
        name: "Leia Skywalker",
        gender: "Female",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/5.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 6,
        name: "Obi Wan Kenobi",
        gender: "Male",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/6.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
    {
        id: 7,
        name: "Lady L",
        gender: "Female",
        homeworld: "Tatooine",
        picture: "https://starwars-visualguide.com/assets/img/characters/7.jpg",
        description: {
            birthYear: "Placeholder",
            height: "Placeholder",
            mass: "Placeholder",
            skinColor: "Placeholder",
            hairColor: "Placeholder",
            eyeColor: "Placeholder",
        },
    },
];

const mockedFilms = [
    {
        id: 1,
        title: "A New Hope",
        cover: "https://starwars-visualguide.com/assets/img/films/1.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 2,
        title: "The Empire Strikes Back",
        cover: "https://starwars-visualguide.com/assets/img/films/2.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 3,
        title: "Return of the Jedi",
        cover: "https://starwars-visualguide.com/assets/img/films/3.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 4,
        title: "The Phantom Menace",
        cover: "https://starwars-visualguide.com/assets/img/films/4.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 5,
        title: "Attack of the Clones",
        cover: "https://starwars-visualguide.com/assets/img/films/5.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
    {
        id: 6,
        title: "Revenge of the Sith",
        cover: "https://starwars-visualguide.com/assets/img/films/6.jpg",
        director: "George Lucas",
        description: mockedDescription,
        characters: mockedCharacters,
    },
];

module.exports = { mockedFilms, mockedCharacters };
